# fly.toml app configuration file generated for rest-api-reply-model on 2024-12-27T14:48:35Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'rest-api-reply-model'
primary_region = 'gig'

[build]
  # Adicionado o Dockerfile para construção, caso necessário
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
